/* Browser tests, run separately from the node --test suite in tests/.

   The two suites answer different questions. The node suite reads what the
   build published: it never opens the page, so it can say which bytes shipped
   but not what the browser does with them. These specs open that published
   page in Chromium and ask the browser itself.

   The split used to run through a DOM simulator, which booted the page without
   a browser but had no accessibility tree and no layout, so it could only
   check that the page set a property; it could not check what the property
   does. That gap let a real bug ship: pausing painted the digits transparent,
   which hid the board from sight and from nobody else, while all 81 cells
   stayed in the accessibility tree and in the tab order. It was found by hand
   in Chrome. Everything in e2e/ is there because only a real browser can
   answer it, and the simulator has been removed: the tests it ran live here
   now, and @playwright/test is the only dependency they need. */

import { defineConfig, devices } from '@playwright/test';

const PORT = Number(process.env.PLAYWRIGHT_PORT || 4173);
/* The site is published as a project site at /sudoku/, so the local server
   mounts the build output under the same prefix. A path that starts with a
   slash then fails here the way it fails in production instead of resolving to
   the account root by accident. */
const BASE_PATH = 'sudoku';
const BASE_URL = `http://127.0.0.1:${PORT}/${BASE_PATH}/`;

export default defineConfig({
  /* node --test claims every file matching *.test.*, wherever it sits. The
     browser specs are named *.spec.mjs and live outside tests/ so the two
     runners never load each other's files. */
  testDir: './e2e',
  testMatch: /.*\.spec\.mjs$/,

  /* Artifacts land inside node_modules on purpose. tests/typography.test.mjs
     walks every file under the repository root and reads it as utf8; a binary
     trace zip can decode into a banned character by chance and fail an
     unrelated test. node_modules is the one tree that walk skips, and these
     files are regenerated by every run anyway. */
  outputDir: './node_modules/.cache/playwright',

  fullyParallel: true,
  /* A .only left in a spec silently shrinks CI to one test. */
  forbidOnly: !!process.env.CI,
  /* Shared runners are slower and noisier than a laptop. Retries absorb that;
     the report still shows which tests needed one. */
  retries: process.env.CI ? 2 : 0,
  /* Puzzle generation blocks the main thread, so parallel workers on a
     two-core runner mostly contend with each other. */
  workers: process.env.CI ? 1 : undefined,

  /* Generous enough for a cold browser start on CI hardware, short enough that
     a hang fails the job rather than sitting until the job timeout. */
  timeout: 30_000,
  expect: { timeout: 10_000 },

  reporter: process.env.CI ? [['github'], ['list']] : [['list']],

  use: {
    baseURL: BASE_URL,
    headless: true,
    trace: 'on-first-retry',
  },

  /* Chromium only. These specs assert on the accessibility tree Chrome builds,
     which is read over CDP, so there is nothing here another engine could run. */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: {
    /* Built first, and served from _site: these specs assert on the bytes the
       deploy uploads rather than on source files the allowlist may never
       publish. The build is a copy of a handful of files, so paying for it on
       every run is cheaper than reasoning about a stale one. */
    command: `node scripts/build.mjs && node e2e/static-server.mjs ${PORT} ${BASE_PATH}`,
    url: BASE_URL,
    /* Never reuse. This repository is normally checked out into several
       worktrees at once, and every one of them serves a different _site on
       this same fixed port. Reusing whatever already holds the port runs the
       entire browser suite against another worktree's build and reports it
       green, which is far worse than a collision: the run says nothing at all
       while looking like it said everything. With this false a busy port is a
       loud startup failure, and PLAYWRIGHT_PORT is how two runs coexist.
       Do not turn this back on to save a few seconds of rebuild. */
    reuseExistingServer: false,
    timeout: 30_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
});
