/* Em dashes, en dashes and middle dots are not used in this project, in shipped
   copy or in source comments. This test is the guard: without it they creep
   back in one commit at a time. */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Written as escapes, not literals, so this file does not trip its own check. */
const BANNED = [
  ['\u2014', 'EM DASH'],
  ['\u2013', 'EN DASH'],
  ['\u00B7', 'MIDDLE DOT'],
  ['\u2012', 'FIGURE DASH'],
  ['\u2015', 'HORIZONTAL BAR'],
];

/* package-lock.json is generated by npm, so its contents are not ours to police. */
const SKIP_DIRS = new Set(['node_modules', '.git', '_site']);
const SKIP_FILES = new Set(['package-lock.json']);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (!SKIP_DIRS.has(entry)) out.push(...walk(full));
    } else if (!SKIP_FILES.has(entry)) {
      out.push(full);
    }
  }
  return out;
}

test('no em dashes, en dashes or middle dots anywhere in the source', () => {
  const offences = [];

  for (const file of walk(root)) {
    let text;
    try {
      text = readFileSync(file, 'utf8');
    } catch {
      continue;
    }
    text.split('\n').forEach((line, i) => {
      for (const [char, name] of BANNED) {
        if (line.includes(char)) {
          offences.push(`${relative(root, file)}:${i + 1} [${name}] ${line.trim().slice(0, 90)}`);
        }
      }
    });
  }

  assert.deepEqual(
    offences,
    [],
    `use a comma, colon, semicolon or a rewritten sentence instead:\n  ${offences.join('\n  ')}`,
  );
});
